# Generated by Django 3.2.4 on 2021-07-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='author',
        ),
    ]
